In [232]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [233]:
df = pd.read_csv('Sample - SuperstoreClean.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2020-103800,3/1/2020,7/1/2020,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.45,2,0.2,5.55
1,2,US-2020-112326,4/1/2020,8/1/2020,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.54,2,0.8,-5.49
2,3,US-2020-112326,4/1/2020,8/1/2020,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.78,3,0.2,4.27
3,4,US-2020-112326,4/1/2020,8/1/2020,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.74,3,0.2,-64.77
4,5,US-2020-141817,5/1/2020,12/1/2020,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.54,3,0.2,4.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2023-143259,30/12/2023,3/1/2024,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.78,3,0.2,19.79
10190,10191,US-2023-115427,30/12/2023,3/1/2024,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.72,2,0.2,6.48
10191,10192,US-2023-156720,30/12/2023,3/1/2024,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.02,3,0.2,-0.60
10192,10193,US-2023-143259,30/12/2023,3/1/2024,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.93,7,0.0,2.73
10193,10194,CA-2023-143500,30/12/2023,3/1/2024,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.02,3,0.2,-0.60

In [234]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

In [235]:
df.describe()

             Row ID        Sales      Quantity      Discount        Profit
count  10194.000000  10194.00000  10194.000000  10194.000000  10194.000000
mean    5097.500000    228.22587      3.791838      0.155385     28.673475
std     2942.898656    619.90687      2.228317      0.206249    232.465210
min        1.000000      0.44000      1.000000      0.000000  -6599.980000
25%     2549.250000     17.22000      2.000000      0.000000      1.760000
50%     5097.500000     53.91000      3.000000      0.200000      8.690000
75%     7645.750000    209.50000      5.000000      0.200000     29.297500
max    10194.000000  22638.48000     14.000000      0.800000   8399.980000

In [236]:
df.shape

(10194, 21)

In [237]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [238]:
# Remove Unique ID
df = df.drop(['Row ID', 'Order ID', 'Customer ID', 'Customer Name', 'Postal Code', 'Ship Date',], axis=1)
df.shape
print(df.columns)
print(len(df.columns))

Index(['Order Date', 'Ship Mode', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')
15

In [239]:
df['Product Name'].value_counts()
print(df['Product Name'].unique())

['Message Book, Wirebound, Four 5 1/2" X 4" Forms/Pg., 200 Dupl. Sets/Book'
 'GBC Standard Plastic Binding Systems Combs' 'Avery 508' ... 'Xerox 1901'
 'Panasonic Business\xa0Telephones\xa0KX-T7736'
 'Bush Saratoga Collection 5-Shelf Bookcase, Hanover Cherry, *Special Order']

In [240]:
import datetime as dt
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Order Date'] = df['Order Date'].map(dt.datetime.toordinal)
print(df['Order Date'].head())
print(df['Order Date'].dtype)

0    737427
1    737428
2    737428
3    737428
4    737429
Name: Order Date, dtype: int64
int64

In [241]:
print(df.columns)
print(df.info())

Index(['Order Date', 'Ship Mode', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order Date      10194 non-null  int64
 1   Ship Mode       10194 non-null  object
 2   Segment         10194 non-null  object
 3   Country/Region  10194 non-null  object
 4   City            10194 non-null  object
 5   State/Province  10194 non-null  object
 6   Region          10194 non-null  object
 7   Product ID      10194 non-null  object
 8   Category        10194 non-null  object
 9   Sub-Category    10194 non-null  object
 10  Product Name    10194 non-null  object
 11  Sales           10194 non-null  float64
 12  Quantity        10194 non-null  int64
 13  Discount        10194 non-null  float64
 14  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(10)
memory usage: 1.2+ MB
None

In [242]:
columns = [ele for ele in (df.columns)]
columns.remove('Order Date')
columns.remove('Sales')
columns.remove('Quantity')
columns.remove('Discount')
columns.remove('Profit')
print(columns)
print(len(columns))

['Ship Mode', 'Segment', 'Country/Region', 'City', 'State/Province', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name']
10

In [243]:

for col in columns:
    dictionary = {}
    # print(col)
    # make dict to mapping value
    for index, item in enumerate((df[col].unique())):
        dictionary[item] = index
    df[col] = df[col].map(dictionary).astype(int)
print(df)

       Order Date  Ship Mode  Segment  Country/Region  City  State/Province  \
0          737427          0        0               0     0               0
1          737428          0        1               0     1               1
2          737428          0        1               0     1               1
3          737428          0        1               0     1               1
4          737429          0        0               0     2               2
...           ...        ...      ...             ...   ...             ...
10189      738884          0        0               0    26              21
10190      738884          0        2               0   172               5
10191      738884          0        0               0   509              27
10192      738884          0        0               0    26              21
10193      738884          0        0               1   276              51

       Region  Product ID  Category  Sub-Category  Product Name   Sales  \
0           0           0         0             0             0   16.45
1           0           1         0             1             1    3.54
2           0           2         0             2             2   11.78
3           0           3         0             3             3  272.74
4           1           4         0             4             4   19.54
...       ...         ...       ...           ...           ...     ...
10189       1         384         0             1           379   52.78
10190       3           8         0             1          1441   20.72
10191       3        1390         0             6          1375    3.02
10192       1        1575         2             7          1561   90.93
10193       1         833         0             1           820    3.02

       Quantity  Discount  Profit
0             2       0.2    5.55
1             2       0.8   -5.49
2             3       0.2    4.27
3             3       0.2  -64.77
4             3       0.2    4.88
...         ...       ...     ...
10189         3       0.2   19.79
10190         2       0.2    6.48
10191         3       0.2   -0.60
10192         7       0.0    2.73
10193         3       0.2   -0.60

[10194 rows x 15 columns]